# Generated by Django 4.2.1 on 2023-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
